<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" <?php echo $settings['languageAttributes']; ?>>

<head profile="http://gmpg.org/xfn/11">
<meta http-equiv="Content-Type" content="<?php echo $settings['htmlType']; ?>; charset=<?php echo $settings['charset']; ?>;" />

<title><?php echo $settings['name']; ?></title>

<link rel="stylesheet" href="<?php echo $settings['cssFolder']; ?>/style.css" type="text/css" media="screen" /> 
<link rel="shortcut icon" href="/favicon.ico" />

<style type="text/css" media="screen">
	#page { background: url("<?php echo $settings['imgFolder']; ?>/kubrickbgwide.jpg") repeat-y top; border: none; }
</style>

</head>
<body>
<div id="page">


<div id="header">
	<div id="headerimg">
		<h1><a href="/blog/"><?php echo $settings['name']; ?></a></h1>
		<div class="description"><?php echo $settings['description']; ?></div>
	</div>
</div>
<hr />
